// Mock HN data — stories, comments, user state

const STORIES = [
  {
    id: 41001,
    title: "Show HN: I built a local-first calendar that syncs over Iroh",
    url: "github.com/ada/orrery",
    points: 487,
    by: "ada_lkp",
    time: "3h",
    descendants: 142,
    type: "show",
    favorite: true,
    note: "Look at their CRDT layer — might apply to our doc editor.",
  },
  {
    id: 41002,
    title: "The compiler is not your friend, and other myths about LLVM",
    url: "boats.gitlab.io",
    points: 312,
    by: "withoutboats",
    time: "5h",
    descendants: 89,
    type: "top",
  },
  {
    id: 41003,
    title: "Ask HN: What's the most interesting thing you've debugged in 2026?",
    url: null,
    points: 244,
    by: "tptacek",
    time: "2h",
    descendants: 311,
    type: "ask",
    favorite: true,
    note: "Save for weekend reading.",
  },
  {
    id: 41004,
    title: "Tauri 3.0 ships with WebView2 parity on macOS via WebKit pinning",
    url: "tauri.app",
    points: 612,
    by: "lucasfernog",
    time: "6h",
    descendants: 198,
    type: "top",
  },
  {
    id: 41005,
    title: "A pragmatic guide to running Postgres on NVMe in 2026",
    url: "crunchydata.com",
    points: 198,
    by: "samokhvalov",
    time: "4h",
    descendants: 54,
    type: "top",
  },
  {
    id: 41006,
    title: "Show HN: Cervantes — a serif-first reader for Hacker News",
    url: "github.com/polaris/cervantes",
    points: 1042,
    by: "polaris_data",
    time: "1h",
    descendants: 287,
    type: "show",
  },
  {
    id: 41007,
    title: "The lost art of structured procrastination, revisited",
    url: "structuredprocrastination.com",
    points: 156,
    by: "jperla",
    time: "7h",
    descendants: 41,
    type: "top",
  },
  {
    id: 41008,
    title: "Apple Silicon M5 benchmarks: a deep dive into the new GPU pipeline",
    url: "anandtech.com",
    points: 823,
    by: "ryans",
    time: "9h",
    descendants: 412,
    type: "top",
    favorite: true,
    note: "Useful for the macOS perf doc.",
  },
  {
    id: 41009,
    title: "Why we replaced Redis with SQLite in production",
    url: "fly.io/blog",
    points: 521,
    by: "mrkurt",
    time: "11h",
    descendants: 226,
    type: "top",
  },
  {
    id: 41010,
    title: "Ask HN: How do you read papers without losing the thread?",
    url: null,
    points: 89,
    by: "annie_p",
    time: "5h",
    descendants: 73,
    type: "ask",
  },
  {
    id: 41011,
    title: "An interactive history of the Lisp machines",
    url: "fare.tunes.org",
    points: 401,
    by: "fare",
    time: "8h",
    descendants: 117,
    type: "top",
  },
  {
    id: 41012,
    title: "Show HN: Tiny VM that runs JavaScript in 32 KB of RAM",
    url: "github.com/jamesm/microjs",
    points: 267,
    by: "jamesm",
    time: "10h",
    descendants: 64,
    type: "show",
  },
  {
    id: 41013,
    title: "The economics of self-hosted email in 2026",
    url: "migadu.com/blog",
    points: 178,
    by: "rsync",
    time: "12h",
    descendants: 95,
    type: "top",
  },
  {
    id: 41014,
    title: "We are hiring a systems engineer — Recurse Center (Remote)",
    url: "recurse.com/jobs",
    points: 0,
    by: "rc_jobs",
    time: "4h",
    descendants: 0,
    type: "job",
  },
];

const COMMENTS = {
  41006: [
    {
      id: "c1",
      by: "tptacek",
      time: "47 min",
      points: 84,
      text: "Genuinely nice to see a reader that doesn't try to reinvent the threading model. The serif is doing a lot of heavy lifting here — it reads like a long-form magazine, not a forum.",
      children: [
        {
          id: "c1-1",
          by: "polaris_data",
          time: "31 min",
          points: 42,
          text: "Thanks. We tested a half-dozen pairings before landing on Source Serif. The big thing was making sure metadata (points, timestamps, usernames) sat in a monospace so the reading column stayed quiet.",
          children: [
            {
              id: "c1-1-1",
              by: "jrockway",
              time: "12 min",
              points: 11,
              text: "Have you tried Charter? It's what Matthew Butterick recommends and it ships with macOS for free.",
              children: [],
            },
          ],
        },
        {
          id: "c1-2",
          by: "kalium",
          time: "22 min",
          points: 9,
          text: "Agreed, although I'd push back gently on the off-white background. On my OLED it's noticeably warm. Could be a per-display setting.",
          children: [],
        },
      ],
    },
    {
      id: "c2",
      by: "withoutboats",
      time: "1h",
      points: 56,
      text: "The favorites pane with notes is the feature I didn't know I wanted. Half the value of HN for me is finding something good and never being able to find it again three weeks later.",
      children: [
        {
          id: "c2-1",
          by: "polaris_data",
          time: "58 min",
          points: 18,
          text: "Exactly the problem we built it for. Tags + a free-text note per favorite, plus a search across only your saved items.",
          children: [],
        },
      ],
    },
    {
      id: "c3",
      by: "patio11",
      time: "2h",
      points: 38,
      text: "Curious whether you considered an iPad version. The reading experience would translate well, and the lack of a serious HN reader on tablet has been a quiet complaint for years.",
      children: [],
    },
    {
      id: "c4",
      by: "antirez",
      time: "2h",
      points: 27,
      text: "Beautiful. One small request: keyboard shortcuts for j/k navigation and o to open in browser, in the vim tradition.",
      children: [
        {
          id: "c4-1",
          by: "polaris_data",
          time: "1h",
          points: 14,
          text: "Already in. j/k for stories, J/K for comments, o for source, c for comments, f to favorite, / for search.",
          children: [],
        },
      ],
    },
  ],
};

// Default comments for any story without an explicit thread
const FALLBACK_COMMENTS = [
  {
    id: "f1",
    by: "ssrinivasan",
    time: "1h",
    points: 31,
    text: "This is the kind of post that reminds me why I still check HN every morning. The comments are usually better than the article, and this one is no exception.",
    children: [
      {
        id: "f1-1",
        by: "dredmorbius",
        time: "42 min",
        points: 12,
        text: "Strong agree. Though the signal-to-noise ratio has shifted noticeably in the last two years. The really thoughtful threads are now buried under three or four layers of meta-commentary.",
        children: [],
      },
    ],
  },
  {
    id: "f2",
    by: "jacquesm",
    time: "2h",
    points: 18,
    text: "There's a related thread from 2019 that covers a lot of the same ground — worth digging up if anyone has the link handy. I remember the conclusion was roughly the opposite of what's being argued here.",
    children: [],
  },
  {
    id: "f3",
    by: "luu",
    time: "3h",
    points: 9,
    text: "The methodology section is doing a lot of work. I'd want to see the raw data before drawing any of these conclusions, but it's a thought-provoking framing either way.",
    children: [],
  },
];

const SECTIONS = [
  { id: "top",    label: "Top",     hint: "Front page", count: 30 },
  { id: "new",    label: "New",     hint: "Newest",     count: 47 },
  { id: "best",   label: "Best",    hint: "Highest-voted recently", count: 30 },
  { id: "ask",    label: "Ask HN",  hint: "Questions",  count: 12 },
  { id: "show",   label: "Show HN", hint: "Projects",   count: 18 },
  { id: "jobs",   label: "Jobs",    hint: "Hiring",     count: 9  },
];

const FAVORITE_TAGS = [
  { id: "read-later",  label: "Read later",  color: "warn"    },
  { id: "tools",       label: "Tools",       color: "accent"  },
  { id: "deep-dive",   label: "Deep dives",  color: "ink"     },
  { id: "saved",       label: "Saved",       color: "muted"   },
];

Object.assign(window, { STORIES, COMMENTS, FALLBACK_COMMENTS, SECTIONS, FAVORITE_TAGS });
